#!/usr/bin/env python3

import xlsxwriter
import io
import string
import sys


# Which column to read
COLUMN = "Concordance"

# Which characters are considered to be part of a word
WORDCHAR = set(string.ascii_letters + string.digits + "-'")


class Convert:
    def __init__(self, marker):
        self.marker = marker

    def parse_tsv(self, s):
        # Wordsmith seems to use non-breaking spaces as thousand separators.
        # We will remove all of them.
        return s.replace(u"\u00A0", "").rstrip("\n").split("\t")

    def read_tsv(self):
        return self.parse_tsv(self.f.readline())

    def find_rword(self, conc):
        m = conc.index(self.marker)
        m2 = conc.rindex(self.marker)
        assert m == m2
        tail = m + len(self.marker)
        text = conc[:m] + conc[tail:]
        x = m
        y = m
        while x > 1 and text[x-1] in WORDCHAR:
            x -= 1
        while y < len(text) - 1 and text[y] in WORDCHAR:
            y += 1
        return text[:x], text[x:y], text[y:]

    def cleanup_word(self, rword):
        return rword.lower()

    def new_row(self, orow, nconc):
        nrow = []
        for i, v in enumerate(orow):
            if i == self.conci:
                nrow.extend(nconc)
            else:
                nrow.append(v)
        return nrow

    def process_head(self):
        # Row 1
        l = self.read_tsv()
        assert len(l) == 1
        assert l[0].startswith("WordSmith Tools ")

        # Row 2
        l = self.read_tsv()
        assert len(l) == 1
        assert l[0] == ""

        # Row 3
        self.header = self.read_tsv()
        self.conci = self.header.index(COLUMN)

        nheader = self.new_row(
            self.header,
            ["Before", "Word", "After", "Simple"],
        )
        for c, elem in enumerate(nheader):
            self.worksheet.write(0, c, elem)

    def process_rest(self):
        r = 1
        while True:
            l = self.f.readline()
            if l == '':
                break
            row = self.parse_tsv(l)
            assert len(self.header) == len(row)
            conc = row[self.conci]
            pre, rword, post = self.find_rword(conc)
            word = self.cleanup_word(rword)
            nrow = self.new_row(row, [pre, rword, post, word])
            for c, elem in enumerate(nrow):
                self.worksheet.write_string(r, c, elem)
            r += 1

    def define_formats(self):
        self.format_head = self.workbook.add_format({'bold': True})
        self.format_right = self.workbook.add_format({'align': 'right'})

    def set_formats(self):
        self.worksheet.set_row(0, None, self.format_head)
        self.worksheet.set_column(self.conci, self.conci, None, self.format_right)

    def convert(self, filein, fileout):
        self.workbook = xlsxwriter.Workbook(fileout)
        self.define_formats()
        self.worksheet = self.workbook.add_worksheet()
        self.f = open(filein, encoding='iso-8859-1')
        self.process_head()
        self.process_rest()
        self.set_formats()
        self.workbook.close()
        self.f.close()


def main():
    param = sys.argv[1:]
    if len(param) != 3:
        sys.exit('usage: {} MARKER INPUT OUTPUT'.format(sys.argv[0]))
    marker, filein, fileout = param

    conv = Convert(marker)
    conv.convert(filein, fileout)


main()
